function p = detection_parameters_interface4(p)


%% setting up the figure, panels and buttons
fh = figure(...
                  'Units','characters',...
                  'NumberTitle','off',...
                  'MenuBar','none',...
                  'Toolbar','none',...
                  'Name','Select Detection/Quantification Parameters',...
                  'Position',[10 10 92 42],...
                  'Visible','off'); 
              
%% attach parameters to figure
% parameters are attached to the dummy figure
% this way they can be shared by all Callback functions
setappdata(fh,'params', p);               

%% psf settings
hpsf = uipanel('parent',fh,'Title','PSF Width (Pix)','Units','characters',...
    'Position',[5 32 26 9]);
        
uicontrol('parent',hpsf,'Units','characters',...
            'HorizontalAlignment','left',...
            'Style','text','String','PSF sigma xy',...
            'Position',[1,5,15,1.5]);           
hsxy = uicontrol('parent',hpsf,'Tag','hsxy',...
            'Units','characters',...
            'Style','edit','String',num2str(p.sigma_xy),...
            'Position',[16,5,7,1.5]);   
        
if p.numdim ==3
    uicontrol('parent',hpsf,'Units','characters',...
                'HorizontalAlignment','left',...
                'Style','text','String','PSF sigma z',...
                'Position',[1,3,15,1.5]);       
    uicontrol('parent',hpsf,'Tag','hsz',...
                'Units','characters',...
                'Style','edit','String',num2str(p.sigma_z),...
                'Position',[16,3,7,1.5]);  
end        
hpsfm = uicontrol('parent',hpsf,'Tag','hpsf_manual',...
            'Units','characters',...
            'Style','Radio',...
            'String','Set Manually',...
            'Position',[1,1,20,1.5]);
set(hpsfm,'Value',p.set_psf_manually);        

%% ROI vs. Full Image
if ~strcmp(p.mode,'directory input')
    hth = uibuttongroup('parent',fh,'Units','characters',...
            'Tag','hROIchoose',...
            'Title','ROI?',...
            'Position',[32 32 11 9]);
        uicontrol('parent',hth,'Style','Radio','Units','characters',...
            'String','No',...
            'Tag','hnoROI',...
            'Position',[1 3.5 8 1.5]);
        hyes = uicontrol('parent',hth,'Style','Radio','Units','characters',...
            'String','Yes',...
            'Tag','hROI',...
            'Position',[1 1.5 8 1.5]); 
    if isfield(p,'select_ROI')
        if p.select_ROI ==1
            set(hth,'SelectedObject',hyes);
        end
    end
end

%% Threshold Settings
hthresh = uipanel('parent',fh,'Title','Detection Threshold',...
    'Units','characters',...
    'Position',[44 32 38 9]);
        
uicontrol('parent',hthresh,'Units','characters',...
            'Style','text','String','Threshold Value :',...
            'Position',[2.5,6,17,1.5]);
uicontrol('parent',hthresh,'Units','characters',...
            'Tag','hthresh_level',...
            'Style','edit','String',num2str(p.thresh.level),...
            'Position',[20.5,6,10,1.5]);
        
hth = uibuttongroup('parent',hthresh,'Units','characters',...
        'Tag','hthresh_units',...
        'Title','Units',...
        'Position',[2.5 0.2 20 6]);
        habs = uicontrol('parent',hth,'Style','Radio','Units','characters',...
            'String','Absolute',...
            'Tag','Absolute',...
            'Position',[1 3 18 1.5]); 
        hSD = uicontrol('parent',hth,'Style','Radio','Units','characters',...
            'String','Intensity S.D.',...
            'Tag','SD',...
            'Position',[1 1.5 18 1.5]);
        if p.AIRLOCALIZE_version ~= 1
            hauto = uicontrol('parent',hth,'Style','Radio','Units','characters',...
                'String','Automatic',...
                'Tag','Automatic',...
                'Position',[1 0 18 1.5]);
        end
        
if isfield(p,'thresh')
    if isfield(p.thresh,'units')
        if strcmp(p.thresh.units,'absolute')
            set(hth,'SelectedObject',habs);
        elseif strcmp(p.thresh.units,'SD')  
            set(hth,'SelectedObject',hSD);
        elseif strcmp(p.thresh.units,'automatic')
            if p.AIRLOCALIZE_version ~= 1
                set(hth,'SelectedObject',hauto);
            else
                set(hth,'SelectedObject',hSD);
            end
        end
    end
end

hthm = uicontrol('parent',hthresh,'Tag','hthresh_manual',...
            'Units','characters',...
            'Tag','hthresh_manually',...
            'String','Set',...
            'Style','Radio',...
            'Position',[23,2.5,10,1.5]);
set(hthm,'Value',p.set_thresh_manually); 

uicontrol('parent',hth,'Units','characters',...
            'Style','text','String','Manually',...
            'Position',[23,1,10,1.5]);        

%% Saving Settings
hsave = uipanel('parent',fh,'Title','Saving Settings',...
    'Units','characters',...
    'Position',[5 24 77 7.5]);

hman = uicontrol('parent',hsave,'Units','characters',...
            'Tag','houtput_spot_img',...
            'Style','Radio','String','Output Image of Spots?',...
            'HorizontalAlignment','left',...
            'Position',[1,4.5,35,1.5]);
        
if isfield(p,'output_spot_image')        
    set(hman,'Value',p.output_spot_image); 
end

uicontrol('parent',hsave,'Units','characters',...
            'HorizontalAlignment','left',...
            'Style','Text','String','Saving Directory',...
            'Position',[1,2,74,1.5]);
uicontrol('parent',hsave,'Units','characters',...
            'Tag','hsave',...
            'Style','edit','String',num2str(p.save_dirname),...
            'Position',[1,0.5,74,1.5]);

%% Advanced Settings
hadv = uipanel('parent',fh,'Title','Advanced Parameters',...
    'Units','characters',...
    'Position',[5 3.5 77 20]);

if p.AIRLOCALIZE_version ~= 1
    hdense = uipanel('parent',hadv,'Units','characters',...
            'Tag','hdense',...
            'Title','Dense Spots',...
            'Position',[36 16.5 39 2.5]);
    hdense_inclusive = uicontrol('parent',hdense,'Style','Radio','Units','characters',...
                'Tag','hdense_inclusive',...
                'String','Treat All',...
                'Position',[1 0 12 1.5]);
    hdense_exclusive = uicontrol('parent',hdense,'Style','Radio','Units','characters',...
                'Tag','hdense_exclusive',...
                'String','Only Selected',...
                'Position',[18 0 20 1.5]); 
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
%voxel size
uicontrol('parent',hadv,'Units','characters',...
            'Style','Text','String','Voxel Width (nm)',...
            'Position',[48,14.8,18,1.2]);
uicontrol('parent',hadv,'Units','characters',...
            'Tag','hdx',...
            'Style','edit','String',num2str(p.dx),...
            'Position',[68,14.8,6,1.2]);
if p.numdim == 3        
    uicontrol('parent',hadv,'Units','characters',...
            'Style','Text','String','Voxel Height (nm)',...
            'Position',[48,13.5,18,1.2]);
    uicontrol('parent',hadv,'Units','characters',...
            'Tag','hdz',...
            'Style','edit','String',num2str(p.dz),...
            'Position',[68,13.5,6,1.2]);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
% detection parameters        
hdet = uipanel('parent',hadv,'Title','Detection',...
    'Units','characters',...
    'Position',[1 0.5 34 18]);        

uicontrol('parent',hdet,'Units','characters',...
            'Style','Text','String','---- Hi pass filter ----',...
            'HorizontalAlignment','left',...
            'Position',[1,15,32,1.5]);
uicontrol('parent',hdet,'Units','characters',...
            'Style','Text','String','Length Cutoff in PSF width units',...
            'HorizontalAlignment','left',...
            'Position',[1,12.25,18,3]);
uicontrol('parent',hdet,'Units','characters',...
            'Tag','hfilter_nlo',...
            'Style','edit','String',num2str(p.filter.nlo),...
            'Position',[19,13.5,12,1.5]); 
        
uicontrol('parent',hdet,'Units','characters',...
            'Style','Text','String','----  Low pass filter ----',...
            'HorizontalAlignment','left',...
            'Position',[1,9.75,32,1.5]);
uicontrol('parent',hdet,'Units','characters',...
            'Style','Text','String','Length Cutoff in pixels',...
            'HorizontalAlignment','left',...
            'Position',[1,7,18,3]);
uicontrol('parent',hdet,'Units','characters',...
            'Tag','hfilter_nhi',...
            'Style','edit','String',num2str(p.filter.nhi),...
            'Position',[19,8.25,12,1.5]);        

uicontrol('parent',hdet,'Units','characters',...
            'Style','Text','String','Cutoff Width (Pix-1)',...
            'HorizontalAlignment','left',...
            'Position',[1,4.5,18,3]);
uicontrol('parent',hdet,'Units','characters',...
            'Tag','hfilter_cutoffwidth',...
            'Style','edit','String',num2str(p.filter.width),...
            'Position',[19,5.75,12,1.5]);         
  
%Minimum allowed distance between predetected spots (Pix)         
uicontrol('parent',hdet,'Units','characters',...
            'Style','Text','String','Min Dist. between Spots (Pix)',...
            'HorizontalAlignment','left',...
            'Position',[0.5,2.5,30,1.5]);
uicontrol('parent',hdet,'Units','characters',...
            'Tag','hROIsize',...
            'Style','edit','String',num2str(p.ROIsize),...
            'Position',[29.5,2.5,3,1.5]); 
        
%Maximum number of predetected spots          
uicontrol('parent',hdet,'Units','characters',...
            'Style','Text','String','Max Spots Count',...
            'HorizontalAlignment','left',...
            'Position',[0.5,0.5,20,1.5]);
uicontrol('parent',hdet,'Units','characters',...
            'Tag','hmax_spots',...
            'Style','edit','String',num2str(p.max_spots),...
            'Position',[21,0.5,10,1.5]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        
% quantification parameters        
hquant =  uipanel('parent',hadv,'Title','Quantification',...
    'Units','characters',...
    'Position',[36 0.5 39 13]); 

%PSF type
uicontrol('parent',hquant,'Units','characters',...
            'Style','Text','String','PSF type',...
            'HorizontalAlignment','left',...
            'Position',[1,10,21,1.5]);
        
if p.numdim == 3
    htypemenu = uicontrol('parent',hquant,'Units','characters',...
            'Tag','htype',...
            'Style','popupmenu','String',...
            {'integrated gaussian std z',...
            'integrated gaussian',...
            'gaussian'},...
            'Position',[23,10.2,14,1.5]);
        
elseif p.numdim == 2
     htypemenu = uicontrol('parent',hquant,'Units','characters',...
             'Tag','htype',...
             'Style','popupmenu','String',...
             {'integrated gaussian',...
             'gaussian'},...
             'Position',[23,10.2,14,1.5]); 
end

if isfield(p,'type')
    switch p.type
        case 'integrated gaussian'
            set(htypemenu,'Value',ceil(p.numdim-1));
        case 'gaussian'
            set(htypemenu,'Value',ceil(p.numdim));
        case 'integrated gaussian std z' 
            set(htypemenu,'Value',1);
    end
end

%Method of quantification
uicontrol('parent',hquant,'Units','characters',...
            'Style','Text','String','Quantification Method',...
            'HorizontalAlignment','left',...
            'Position',[1,8,21,1.5]);
        
if p.numdim == 3
    hmethmenu = uicontrol('parent',hquant,'Units','characters',...
            'Tag','hmethod',...
            'Style','popupmenu','String',...
            {'3D mask full',...
            '2D mask on local max projection',...
            '3D gaussian fit'},...
            'Position',[23,8.2,14,1.5]);
        
elseif p.numdim == 2
     hmethmenu = uicontrol('parent',hquant,'Units','characters',...
             'Tag','hmethod',...
             'Style','popupmenu','String',...
             {'2D gaussian mask',...
             '2D gaussian fit'},...
             'Position',[23,8.2,14,1.5]); 
end

if isfield(p,'fit')
    switch p.fit
        case '3D mask full'
            set(hmethmenu,'Value',1);
        case '2D mask on local max projection'
            set(hmethmenu,'Value',2);
        case '3D gaussian fit'
            if p.numdim == 3
                set(hmethmenu,'Value',3);
            else
                set(hmethmenu,'Value',2);
            end
        case '2D gaussian mask'
            set(hmethmenu,'Value',1);
        case '2D gaussian fit'
            set(hmethmenu,'Value',2);        
    end
end

%size of the fitted region
uicontrol('parent',hquant,'Units','characters',...
            'Style','Text','String','Local Fit Size (PSF units)',...
            'HorizontalAlignment','left',...
            'Position',[1,6,27,1.5]);
uicontrol('parent',hquant,'Units','characters',...
            'Tag','hcutsize',...
            'Style','edit','String',num2str(p.cutsize),...
            'Position',[29,6,6,1.5]); 

%size of the region used for local background subtraction       
uicontrol('parent',hquant,'Units','characters',...
            'Style','Text','String','Local Background Thickness (Pix)',...
            'HorizontalAlignment','left',...
            'Position',[1,4,33,1.5]);
uicontrol('parent',hquant,'Units','characters',...
            'Tag','hthickness',...
            'Style','edit','String',num2str(p.thickness),...
            'Position',[34.5,4,3,1.5]); 

%background correction 
uicontrol('parent',hquant,'Units','characters',...
            'Style','Text','String','background correction',...
            'HorizontalAlignment','left',...
            'Position',[1,2.2,24,1.5]);
        
hbgmenu = uicontrol('parent',hquant,'Units','characters',...
            'Tag','hbg_mode',...
            'Style','popupmenu','String',...
            {'local plane',...
            'local median',...
            'global median'},...
            'Position',[25,2.2,12,1.5]);
        
if isfield(p,'bg_mode')
    switch p.bg_mode
        case 'local plane'
            set(hbgmenu,'Value',1);
        case 'local median'
            set(hbgmenu,'Value',2);
        case 'global median' 
            set(hbgmenu,'Value',3);       
    end
end
        
%convergence tolerance of the gaussian mask       
uicontrol('parent',hquant,'Units','characters',...
            'Style','Text','String','Max Iterations Number',...
            'HorizontalAlignment','left',...
            'Position',[1,0.5,29,1.5]);
uicontrol('parent',hquant,'Units','characters',...
            'Tag','hmaxcount',...
            'Style','edit','String',num2str(p.maxcount),...
            'Position',[30.5,0.5,6,1.5]);
        
%% action buttons        
%next button
hnext = uicontrol('Parent',fh,'Units','characters',...
                    'Style','pushbutton',...
                    'String','next',...
                    'Position',[62,1,20,2]);
%cancel button
hcancel = uicontrol('Parent',fh,'Units','characters',...
                    'Style','pushbutton',...
                    'String','cancel',...
                    'Position',[5,1,20,2]);

%% Callbacks
if p.AIRLOCALIZE_version ~= 1
    set(hdense_inclusive,'Callback',{@radio_safecheck,fh});
    set(hdense_exclusive,'Callback',{@radio_safecheck,fh});
end
set(hnext,'Callback',{@next,fh});                
set(hcancel,'Callback',{@cancel,fh});               
set(fh,'Visible','on');

uiwait;

%% Housekeeping
p = getappdata(fh,'params');
close(fh);
clear('hsave','hpsf','hpsfm','hthresh','hthm','hth','hadv','hdet','hquant','hnext','hcancel');
return;
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function radio_safecheck(src,eventdata,fh)
    handles = guihandles(fh);
    if strcmp(get(src,'Tag'),'hdense_inclusive')
        if get(src,'Value') == 1 && get(handles.hdense_exclusive,'Value') == 1
        	set(handles.hdense_exclusive,'Value',0) 
        end
    elseif strcmp(get(src,'Tag'),'hdense_exclusive')
        if get(src,'Value') == 1 && get(handles.hdense_inclusive,'Value') == 1
        	set(handles.hdense_inclusive,'Value',0) 
        end    
    else
        disp('could not identify src');
    end

end

function next(src,eventdata,fh)
p = getappdata(fh,'params');
handles = guihandles(fh);
p.sigma_xy = str2double(get(handles.hsxy,'String'));
if p.numdim == 3
     p.sigma_z = str2double(get(handles.hsz,'String'));
     p.dz = str2double( get(handles.hdz,'String') ); 
end
method = get(handles.hmethod,'String');
p.fit = method{get(handles.hmethod,'Value')};

psftypes = get(handles.htype,'String');
p.type = psftypes{get(handles.htype,'Value')};

bgstr = get(handles.hbg_mode,'String');
p.bg_mode = bgstr{get(handles.hbg_mode,'Value')};

p.set_psf_manually = get(handles.hpsf_manual,'Value');
if strcmp(p.mode,'directory input')
    p.select_ROI = 0;
else
    p.select_ROI = get(get(handles.hROIchoose,'SelectedObject'),'Tag');
    if strcmp(p.select_ROI,'hROI')
        p.select_ROI = 1;
    else
        p.select_ROI = 0;
    end
end

str_thr = get(get(handles.hthresh_units,'SelectedObject'),'Tag'); 
    
if  strcmp(str_thr,'Absolute') 
    p.thresh.units = 'absolute';
elseif strcmp(str_thr,'SD') 
    p.thresh.units = 'SD';
elseif strcmp(str_thr,'Automatic') 
    p.thresh.units = 'automatic';
end
p.thresh.level = str2double( get(handles.hthresh_level,'String') );
p.save_dirname = get(handles.hsave,'String');
p.set_thresh_manually = get(handles.hthresh_manually,'Value');
p.dx = str2double( get(handles.hdx,'String') ); 
p.dy = p.dx;

p.filter.nlo = str2double( get(handles.hfilter_nlo,'String') ); 
p.filter.nhi = str2double( get(handles.hfilter_nhi,'String') ); 
p.filter.width = str2double( get(handles.hfilter_cutoffwidth,'String') ); 
p.output_spot_image = get(handles.houtput_spot_img,'Value');

if p.AIRLOCALIZE_version ~= 1
    if get(handles.hdense_inclusive,'Value') == 1 && get(handles.hdense_exclusive,'Value') == 0
        p.dense_spots = 1;
        p.dense_mode = 'inclusive';
    elseif get(handles.hdense_inclusive,'Value') == 0 && get(handles.hdense_exclusive,'Value') == 1
        p.dense_spots = 1;
        p.dense_mode = 'exclusive';
    elseif get(handles.hdense_inclusive,'Value') == 0 && get(handles.hdense_exclusive,'Value') == 0
        p.dense_spots = 0;
        if isfield(p,'dense_mode')
            p = rmfield(p,'dense_mode');
        end
    end
else
    p.dense_spots = 0;
    if isfield(p,'dense_mode')
        p = rmfield(p,'dense_mode');
    end
end

p.ROIsize = str2double(get(handles.hROIsize,'String'));
p.thickness = str2double(get(handles.hthickness,'String'));
p.cutsize = str2double(get(handles.hcutsize,'String')); 
p.max_spots = str2double( get(handles.hmax_spots,'String')); 
p.maxcount = str2double(get(handles.hmaxcount,'String'));
setappdata(fh,'params',p);

%% housekeeping
clear('p','handles','method','bgstr');
uiresume
end

function cancel(src,eventdata,fh)
p = getappdata(fh,'params');
p.mode = 'cancel';
setappdata(fh,'params',p);
clear('p');
uiresume
end


