function params = set_detection_mode(params)

%% setting up the figure, panels and buttons
    fh = figure(...
                  'Units','characters',...
                  'MenuBar','none',...
                  'Toolbar','none',...
                  'Name','Select File Mode',...
                  'NumberTitle','off',...
                  'Position',[50 20 80 26],...
                  'Visible','off'); 

    %radio button group to select the type of data input          
    hsel_mode = uibuttongroup('Units','characters',...
        'Title','Choose the type of data do you want to analyze',...
        'Position',[12.5 12 55 13]);
        uicontrol('Style','Radio','Units','characters',...
            'String','2D single image file',...
            'Tag','2D single image file',...
            'Position',[1 9.5 50 2],'parent',hsel_mode);
        uicontrol('Style','Radio','Units','characters',...
            'String','2D images, batch mode',...
            'Tag','2D images, batch mode',...
            'Position',[1 8 50 2],'parent',hsel_mode);
        uicontrol('Style','Radio','Units','characters',...
            'String','2D images from a movie in a directory',...
            'Tag','2D images from a movie in a directory',...
            'Position',[1 6.5 50 2],'parent',hsel_mode);
        uicontrol('Style','Radio','Units','characters',...
            'String','2D movie in a single file',...
            'Tag','2D movie in a single file',...
            'Position',[1 5 50 2],'parent',hsel_mode);
        
        uicontrol('Style','Radio','Units','characters',...
            'String','3D single image file',...
            'Tag','3D single image file',...
            'Position',[1 3.5 50 2],'parent',hsel_mode);
        uicontrol('Style','Radio','Units','characters',...
            'String','3D images, batch mode',...
            'Tag','3D images, batch mode',...
            'Position',[1 2 50 2],'parent',hsel_mode);
        uicontrol('Style','Radio','Units','characters',...
            'String','3D images from a movie',...
            'Tag','3D images from a movie',...
            'Position',[1 0.5 50 2],'parent',hsel_mode);
      
    %Strings that file name must or must not contain for the batch mode:
    hfname_str = uipanel('Units','characters',...
        'Parent',fh,...
        'Title','Optional - batch mode only',...
        'Position',[12.5,4,55,7]);
    
        uicontrol('Parent',hfname_str,'Units','characters',...
            'Style','Text',...
            'String','Name Contains',...
            'Position',[0.5,4,25,1.2]);
        uicontrol('Parent',hfname_str,'Units','characters',...
            'Style','edit',...
            'String','',...
            'Tag','inclusion_string',...
            'Position',[26,4,25,1.5]);
                    
        uicontrol('Parent',hfname_str,'Units','characters',...
            'Style','Text',...
            'String','Name Does Not Contain',...
            'Position',[0.5,2.5,25,1.2]);
        uicontrol('Parent',hfname_str,'Units','characters',...
            'Style','edit',...
            'Tag','exclusion_string',...
            'String','',...
            'Position',[26,2.5,25,1.5]);
        uicontrol('Style','Radio','Units','characters',...
            'String','Explore Subfolders',...
            'Tag','recursive',...
            'Position',[2,0.5,25,1.2],'Parent',hfname_str);
        
    set(hsel_mode,'Visible','on');  
    set(hfname_str,'Visible','on'); 
    set(fh,'Visible','on');
    
    %next button
    hnext = uicontrol('Parent',fh,'Units','characters',...
                        'Style','pushbutton',...
                        'String','next',...
                        'Position',[47.5,1,20,2]);
    %cancel button
    hcancel = uicontrol('Parent',fh,'Units','characters',...
                        'Style','pushbutton',...
                        'String','cancel',...
                        'Position',[12.5,1,20,2]);
    handles = guihandles(fh);
    set(hnext,'Callback',{@get_mode,fh,hsel_mode});                
    set(hcancel,'Callback',{@cancel,fh});                

%% nested callback function
    function get_mode(src,eventdata,fh,hsel_mode)
        
        xtag = get(get(hsel_mode,'SelectedObject'), 'Tag');
        
        
        if strcmp(xtag,'2D single image file')
            params.mode = 'single file input';
            params.numdim = 2;
        elseif strcmp(xtag,'2D images, batch mode')
            params.mode = 'directory input';
            params.numdim = 2;
            params.inclusion_string = get(handles.inclusion_string, 'String');
            params.exclusion_string = get(handles.exclusion_string, 'String');
            %format strings into cell arrays of substrings
            params.inclusion_string = parse_and_format_string_list(params.inclusion_string);
            params.exclusion_string = parse_and_format_string_list(params.exclusion_string);
            if get(handles.recursive, 'Value') == 1
                params.dirmode = 'recursive';
            else
                params.dirmode = 'standard';
            end
        elseif strcmp(xtag,'2D images from a movie in a directory')
            params.mode = 'movie directory input';
            params.numdim = 2;
            params.inclusion_string = get(handles.inclusion_string, 'String');
            params.exclusion_string = get(handles.exclusion_string, 'String');
            %format strings into cell arrays of substrings
            params.inclusion_string = parse_and_format_string_list(params.inclusion_string);
            params.exclusion_string = parse_and_format_string_list(params.exclusion_string); 
            if get(handles.recursive, 'Value') == 1
                params.dirmode = 'recursive';
            else
                params.dirmode = 'standard';
            end
        elseif strcmp(xtag,'2D movie in a single file')
            params.mode = 'movie single file input';
            params.numdim = 2;    
        elseif strcmp(xtag,'3D single image file')
            params.mode = 'single file input';
            params.numdim = 3;
        elseif strcmp(xtag,'3D images, batch mode')
            params.mode = 'directory input';
            params.numdim = 3;
            params.inclusion_string = get(handles.inclusion_string, 'String');
            params.exclusion_string = get(handles.exclusion_string, 'String');
            %format strings into cell arrays of substrings
            params.inclusion_string = parse_and_format_string_list(params.inclusion_string);
            params.exclusion_string = parse_and_format_string_list(params.exclusion_string);
            if get(handles.recursive, 'Value') == 1
                params.dirmode = 'recursive';
            else
                params.dirmode = 'standard';
            end
        elseif strcmp(xtag,'3D images from a movie')
            params.mode = 'movie directory input';
            params.numdim = 3;
            params.inclusion_string = get(handles.inclusion_string, 'String');
            params.exclusion_string = get(handles.exclusion_string, 'String');
            %format strings into cell arrays of substrings
            params.inclusion_string = parse_and_format_string_list(params.inclusion_string);
            params.exclusion_string = parse_and_format_string_list(params.exclusion_string);
            if get(handles.recursive, 'Value') == 1
                params.dirmode = 'recursive';
            else
                params.dirmode = 'standard';
            end
        end
        clear('nt');
        uiresume;
    end
    
%% nested callback function
    function cancel(src,eventdata,fh)
        uiresume;
        params.mode = 'cancel';
    end
    
    %% housepkeeping
    uiwait;
    close(fh);
    clear('hnext','hsel_mode','hcancel','u1','u2','fh');
    return
    
    
    
end