function fh = set_figure_and_panel_for_view_stack_col(stack1,stack1name)


%%%%%%%%%%%%%%%%%%%%% variables initialization %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[~,~,nz] = size(stack1);

strXpos = '1';     % default x value of the current pixel
strYpos = '1';     % default y value of the current pixel
strIval = num2str(stack1(1,1,1));   % value of the intensity @ the current pixel
strZpos = '1';     % the default value for the z stack displayed

%values of global min max and median
Imed = median_stack(stack1);
Isd = std_stack(stack1);
Imin = min(min(min(stack1)));
Imax = max(max(max(stack1)));

strImin = num2str(Imin,'%10.4f');
strImax = num2str(Imax,'%10.4f');
strImed = num2str(Imed,'%10.4f');
strIsd = num2str(Isd,'%10.4f');

%values of min max and median of current slice (z=1 when you open the viewer)
curImin = min(min(stack1(:,:,1)));
curImax = max(max(stack1(:,:,1)));
curImed = median_im(stack1(:,:,1));
curIsd = std_im(stack1(:,:,1));

strcurImin = num2str(curImin,'%10.4f');
strcurImax = num2str(curImax,'%10.4f');
strcurImed = num2str(curImed,'%10.4f');
strcurIsd = num2str(curIsd,'%10.4f');

%default values of the ranges of the 3 axial views
xpix = num2str(50);
ypix = num2str(50);
zpix = num2str(50);

%default value of the size of the zoom window.
startzoomwidth = num2str(50);

%% %%%%%%%%%%%%%%%%%%%%%%% main figure, plots and title %%%%%%%%%%%%%%%%%%%%%%%
fh = figure(...
              'Units','characters',...
              'MenuBar','none',...
              'Toolbar','none',...
              'Position',[20 3 200 55],...
              'Visible','off');   

set(fh,'Toolbar','figure');
set(fh,'Name',stack1name);              
axes('Units','Pixels','Position',[10,6.15,102.4,39.4],'Tag','ha');     %main figure
        
axes('Parent',fh,'Units','characters','Position',[120 45.4 66 7.7],'Tag','xh'); 
axes('Parent',fh,'Units','characters','Position',[120 33.8 66 7.7],'Tag','yh'); 
axes('Parent',fh,'Units','characters','Position',[120 22.3 66 7.7],'Tag','zh'); 

%% %%%%%%%%%%%%%%%%%%%%%%%%% settings for the axial views %%%%%%%%%%%%%%%%
uicontrol('Units','characters',...
                'Style','text','String','profile along x',...
                'Position',[720,693,100,15]);
uicontrol('Units','pixels',...
                'Style','text','String','profile along y',...
                'Position',[720,543,100,15]);
uicontrol('Units','pixels',...
                'Style','text','String','profile along z',...
                'Position',[720,393,100,15]);
            
uicontrol('Units','pixels',...
                'Style','text','String','number of voxels to display',...
                'Position',[940,640,50,45]); 
uicontrol('Units','pixels',...
                'Style','text','String','number of voxels to display',...
                'Position',[940,490,50,45]); 
uicontrol('Units','pixels',...
                'Style','text','String','number of voxels to display',...
                'Position',[940,340,50,45]); 

uicontrol('Units','pixels',...
                'Tag','hxplot_range',...
                'Style','edit','String',xpix,...
                'Position',[950,620,30,15]);                  
uicontrol('Units','pixels',...
                'Tag','hyplot_range',...
                'Style','edit','String',ypix,...
                'Position',[950,470,30,15]);            
uicontrol('Units','pixels',...
                'Tag','hzplot_range',...
                'Style','edit','String',zpix,...
                'Position',[950,320,30,15]);

%% %%%%%%%%%%%%%%%%%%%%%%%%% zoom plot %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%            
axes('Parent',fh,'Units','Pixels','Position',[720 25 230 230],'Tag','zoomh');             

uicontrol('Units','pixels',...
                'Style','text','String','window size',...
                'Position',[960,150,40,30]);
            
uicontrol('Units','pixels',...
                'Tag','hzoomwidth',...
                'Style','edit','String',startzoomwidth,...
                'Position',[960,135,30,15]); 

%% %%%%%%%%%%%%%%%%%%%%%%%% fit gaussian %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Units','pixels',...
                'Style','pushbutton','String','local gaussian fit',...
                'Position',[580,230,100,15]);

uicontrol('Units','pixels',...
                'Style','text','String','x max',...
                'Position',[580,200,40,15]);
uicontrol('Units','pixels',...
                'Tag','h_x0',...
                'Style','text','String','undefined',...
                'Position',[630,200,60,15]);
uicontrol('Units','pixels',...
                'Style','text','String','y max',...
                'Position',[580,185,40,15]);
uicontrol('Units','pixels',...
                'Tag','h_y0',...
                'Style','text','String','undefined',...
                'Position',[630,185,60,15]);            
uicontrol('Units','pixels',...
                'Style','text','String','z max',...
                'Position',[580,170,40,15]);
uicontrol('Units','pixels',...
                'Tag','h_z0',...
                'Style','text','String','undefined',...
                'Position',[630,170,60,15]); 
uicontrol('Units','pixels',...
                'Style','text','String','Int. max',...
                'Position',[565,150,70,15]);
uicontrol('Units','pixels',...
                'Tag','hI0',...
                'Style','text','String','undefined',...
                'Position',[630,150,60,15]); 
uicontrol('Units','pixels',...
                'Style','text','String','background',...
                'Position',[565,135,70,15]);
uicontrol('Units','pixels',...
                'Tag','h_bg0',...
                'Style','text','String','undefined',...
                'Position',[630,135,60,15]); 
uicontrol('Units','pixels',...
                'Style','text','String','s_xy',...
                'Position',[580,115,40,15]);
uicontrol('Units','pixels',...
                 'Tag','h_sxy0',...
                'Style','text','String','undefined',...
                'Position',[630,115,60,15]);  
uicontrol('Units','pixels',...
                'Style','text','String','s_z',...
                'Position',[580,100,40,15]);
uicontrol('Units','pixels',...
                'Tag','h_sz0',...
                'Style','text','String','undefined',...
                'Position',[630,100,60,15]);  
                       
            
                 
%% %%%%%%%%%%%%%%%%%%%%%%%%% contrast panel %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ph = uipanel(fh,'Title','Contrast','Units','pixels',...
             'Position',[150 600 415 110],'TitlePosition','centertop');

%info relative to the current slice        
hslice_title =  uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String','current z-plane',...
                'Position',[50,85,90,15]);        

hslice_Imin_Info_title = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String','min',...
                'Position',[0,70,40,15]);            
hslice_Imed_Info_title = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String','median',...
                'Position',[65,70,40,15]);            
hslice_Imax_Info_title = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String','max',...
                'Position',[120,70,40,15]);            
hslice_Isd_Info_title = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String','SD',...
                'Position',[195,70,40,15]);   
            
hslice_Imin_Info_val = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String',strcurImin,...
                'Position',[0,60,40,15]);            
hslice_Imed_Info_val = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String',strcurImed,...
                'Position',[65,60,40,15]);            
hslice_Imax_Info_val = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String',strcurImax,...
                'Position',[120,60,40,15]);  
hslice_Isd_Info_val = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String',strcurIsd,...
                'Position',[195,60,40,15]);  
            
%info on whole stack                        
hglobal_title =  uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String','whole stack',...
                'Position',[50,30,90,15]);        

hglobal_Imin_Info_title = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String','min',...
                'Position',[0,15,40,15]);            
hglobal_Imed_Info_title = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String','median',...
                'Position',[65,15,40,15]);            
hglobal_Imax_Info_title = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String','max',...
                'Position',[120,15,40,15]);            
hglobal_Isd_Info_title = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String','SD',...
                'Position',[195,15,40,15]);
            
hglobal_Imin_Info_val = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String',strImin,...
                'Position',[00,5,40,15]);            
hglobal_Imed_Info_val = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String',strImed,...
                'Position',[65,5,40,15]);            
hglobal_Imax_Info_val = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String',strImax,...
                'Position',[120,5,40,15]);                       
hglobal_Isd_Info_val = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String',strIsd,...
                'Position',[195,5,40,15]);             
            
%contrast settings           
hslice_auto = uicontrol('Parent',ph,'Units','pixels',...
                'Style','pushbutton',...
                'String','auto adjust on current z-plane',...
                'Units','pixels','Position',[260,65,150,25]); 

hglob_auto = uicontrol('Parent',ph,'Units','pixels',...
                'Style','pushbutton',...
                'String','auto adjust on whole stack',...
                'Units','pixels','Position',[260,35,150,25]); 
            
hImintitle = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String','min Int.',...
                'Position',[260,17,60,15]);
       
hImin = uicontrol('Parent',ph,'Units','pixels',...
                'Style','edit','String',strImin,...
                'Position',[260,5,60,15]);         

hImaxtitle = uicontrol('Parent',ph,'Units','pixels',...
                'Style','text','String','max Int.',...
                'Position',[330,17,60,15]);

hImax = uicontrol('Parent',ph,'Units','pixels',...
                'Style','edit','String',strImax,...
                'Position',[330,5,60,15]);                
       
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%% pointer info %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
hxtitle = uicontrol('Style','text','String','x',...
           'Position',[50,630,30,15]);

hstate=uicontrol('style','list','String',...
{'<HTML><FONT COLOR=00FF00>grab</FONT><HTML>',...
'<HTML><FONT COLOR=FF0000>snap</FONT><HTML>'},...
'Position',[600,693,60,15]);       

hxpos = uicontrol('Style','text','String',strXpos,...
           'Position',[70,630,60,15]);       
       
hytitle = uicontrol('Style','text','String','y',...
           'Position',[50,615,30,15]);

hypos = uicontrol('Style','text','String',strYpos,...
           'Position',[70,615,60,15]);       
       
hItitle = uicontrol('Style','text','String','Int',...
           'Position',[50,600,30,15]);

hIval = uicontrol('Style','text','String',strIval,...
           'Position',[70,600,60,15]);

%% %%%%%%%%%%%%%%%%%%%%%%%%%%% z browser %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%       
hzpos = uicontrol(fh,'Style','edit',...
                'String',strZpos,...
                'Position',[270 45 30 15]);

zslider = uicontrol(fh,'Style','slider',...
                'Max',nz,'Min',1,'Value',1,...
                'SliderStep',[1/(nz-1) 1/(nz-1)],...
                'Position',[50 30 512 15]);

hclose = uicontrol(fh,'Style','pushbutton',...
                    'String','close',...
                    'Position',[850 5 50,15]);
                             
clear('nx','ny','nz','strXpos','strYpos','strZpos','Imed','Isd','Imin','Imax','strImin','strImax','strImed','strIsd',...
    'curImin','curImax','curImed','curIsd','strcurImin','strcurImax','strcurImed','strcurIsd','xpix','ypix','zpix',...
    'startzoomwidth');
clear('stack1','stack1name');
end